version: '3'

services:
  postgresql:
    image: postgres:11
    container_name: pg-docker
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped